//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.UpdateServices.WebServices.DssAuthentication
{
    using System.Runtime.Serialization;

#pragma warning disable 1591

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAuthorizationCookieRequestBody", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService")]
    public partial class GetAuthorizationCookieRequestBody : object
    {
        
        private string accountNameField;
        
        private string accountGuidField;
        
        private Microsoft.UpdateServices.WebServices.DssAuthentication.ArrayOfGuid programKeysField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string accountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountGuid
        {
            get
            {
                return this.accountGuidField;
            }
            set
            {
                this.accountGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Microsoft.UpdateServices.WebServices.DssAuthentication.ArrayOfGuid programKeys
        {
            get
            {
                return this.programKeysField;
            }
            set
            {
                this.programKeysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService", ItemName="guid")]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAuthorizationCookieResponseBody", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService")]
    public partial class GetAuthorizationCookieResponseBody : object
    {
        
        private Microsoft.UpdateServices.WebServices.DssAuthentication.AuthorizationCookie GetAuthorizationCookieResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Microsoft.UpdateServices.WebServices.DssAuthentication.AuthorizationCookie GetAuthorizationCookieResult
        {
            get
            {
                return this.GetAuthorizationCookieResultField;
            }
            set
            {
                this.GetAuthorizationCookieResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationCookie", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService")]
    public partial class AuthorizationCookie : object
    {
        
        private string PlugInIdField;
        
        private byte[] CookieDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PlugInId
        {
            get
            {
                return this.PlugInIdField;
            }
            set
            {
                this.PlugInIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] CookieData
        {
            get
            {
                return this.CookieDataField;
            }
            set
            {
                this.CookieDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitoredServicesResponse", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable")]
    public partial class MonitoredServicesResponse : object
    {
        
        private bool SuccessFlagField;
        
        private System.DateTime ServicesTimeField;
        
        private string ServicesNameField;
        
        private string ServicesMachineField;
        
        private bool IsHttpsField;
        
        private string RequestContentTypeField;
        
        private string ConfigFilePathField;
        
        private string ConfigFileProjectNameField;
        
        private string ConfigFileEnvironmentNameField;
        
        private System.DateTime ConfigFileLastModifiedTimeField;
        
        private string ConfigFileVersionField;
        
        private System.DateTime ConfigFileNextExpirationTimeField;
        
        private int ConfigFileExpirationModuloInMinutesField;
        
        private string DatabaseInfoField;
        
        private string CustomInfoField;
        
        private bool DebugModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SuccessFlag
        {
            get
            {
                return this.SuccessFlagField;
            }
            set
            {
                this.SuccessFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime ServicesTime
        {
            get
            {
                return this.ServicesTimeField;
            }
            set
            {
                this.ServicesTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ServicesName
        {
            get
            {
                return this.ServicesNameField;
            }
            set
            {
                this.ServicesNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ServicesMachine
        {
            get
            {
                return this.ServicesMachineField;
            }
            set
            {
                this.ServicesMachineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsHttps
        {
            get
            {
                return this.IsHttpsField;
            }
            set
            {
                this.IsHttpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RequestContentType
        {
            get
            {
                return this.RequestContentTypeField;
            }
            set
            {
                this.RequestContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ConfigFilePath
        {
            get
            {
                return this.ConfigFilePathField;
            }
            set
            {
                this.ConfigFilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ConfigFileProjectName
        {
            get
            {
                return this.ConfigFileProjectNameField;
            }
            set
            {
                this.ConfigFileProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ConfigFileEnvironmentName
        {
            get
            {
                return this.ConfigFileEnvironmentNameField;
            }
            set
            {
                this.ConfigFileEnvironmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime ConfigFileLastModifiedTime
        {
            get
            {
                return this.ConfigFileLastModifiedTimeField;
            }
            set
            {
                this.ConfigFileLastModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ConfigFileVersion
        {
            get
            {
                return this.ConfigFileVersionField;
            }
            set
            {
                this.ConfigFileVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime ConfigFileNextExpirationTime
        {
            get
            {
                return this.ConfigFileNextExpirationTimeField;
            }
            set
            {
                this.ConfigFileNextExpirationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int ConfigFileExpirationModuloInMinutes
        {
            get
            {
                return this.ConfigFileExpirationModuloInMinutesField;
            }
            set
            {
                this.ConfigFileExpirationModuloInMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DatabaseInfo
        {
            get
            {
                return this.DatabaseInfoField;
            }
            set
            {
                this.DatabaseInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CustomInfo
        {
            get
            {
                return this.CustomInfoField;
            }
            set
            {
                this.CustomInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool DebugMode
        {
            get
            {
                return this.DebugModeField;
            }
            set
            {
                this.DebugModeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService", ConfigurationName="Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService")]
    public interface IDSSAuthWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService/GetAuthori" +
            "zationCookie", ReplyAction="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService/IDSSAuthWe" +
            "bService/GetAuthorizationCookieResponse")]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieResponse> GetAuthorizationCookieAsync(Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable/Ping", ReplyAction="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService/IDSSAuthWe" +
            "bService/PingResponse")]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.PingResponse> PingAsync(Microsoft.UpdateServices.WebServices.DssAuthentication.PingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationCookieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService", Order=0)]
        public Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequestBody GetAuthorizationCookie;
        
        public GetAuthorizationCookieRequest()
        {
        }
        
        public GetAuthorizationCookieRequest(Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequestBody GetAuthorizationCookie)
        {
            this.GetAuthorizationCookie = GetAuthorizationCookie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationCookieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationCookieResponse", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/DssAuthWebService", Order=0)]
        public Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieResponseBody GetAuthorizationCookieResponse1;
        
        public GetAuthorizationCookieResponse()
        {
        }
        
        public GetAuthorizationCookieResponse(Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieResponseBody GetAuthorizationCookieResponse1)
        {
            this.GetAuthorizationCookieResponse1 = GetAuthorizationCookieResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable", IsWrapped=true)]
    public partial class PingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable", Order=0)]
        public int pingLevel;
        
        public PingRequest()
        {
        }
        
        public PingRequest(int pingLevel)
        {
            this.pingLevel = pingLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable", IsWrapped=true)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/IMonitorable", Order=0)]
        public Microsoft.UpdateServices.WebServices.DssAuthentication.MonitoredServicesResponse PingResult;
        
        public PingResponse()
        {
        }
        
        public PingResponse(Microsoft.UpdateServices.WebServices.DssAuthentication.MonitoredServicesResponse PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IDSSAuthWebServiceChannel : Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class DSSAuthWebServiceClient : System.ServiceModel.ClientBase<Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService>, Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DSSAuthWebServiceClient() : 
                base(DSSAuthWebServiceClient.GetDefaultBinding(), DSSAuthWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IDSSAuthWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DSSAuthWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DSSAuthWebServiceClient.GetBindingForEndpoint(endpointConfiguration), DSSAuthWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DSSAuthWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DSSAuthWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DSSAuthWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DSSAuthWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DSSAuthWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieResponse> Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService.GetAuthorizationCookieAsync(Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequest request)
        {
            return base.Channel.GetAuthorizationCookieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieResponse> GetAuthorizationCookieAsync(Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequestBody GetAuthorizationCookie)
        {
            Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequest inValue = new Microsoft.UpdateServices.WebServices.DssAuthentication.GetAuthorizationCookieRequest();
            inValue.GetAuthorizationCookie = GetAuthorizationCookie;
            return ((Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService)(this)).GetAuthorizationCookieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.PingResponse> Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService.PingAsync(Microsoft.UpdateServices.WebServices.DssAuthentication.PingRequest request)
        {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.DssAuthentication.PingResponse> PingAsync(int pingLevel)
        {
            Microsoft.UpdateServices.WebServices.DssAuthentication.PingRequest inValue = new Microsoft.UpdateServices.WebServices.DssAuthentication.PingRequest();
            inValue.pingLevel = pingLevel;
            return ((Microsoft.UpdateServices.WebServices.DssAuthentication.IDSSAuthWebService)(this)).PingAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IDSSAuthWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IDSSAuthWebService))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.update.microsoft.com/DSSAuthWebService/DSSAuthWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DSSAuthWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IDSSAuthWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DSSAuthWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IDSSAuthWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IDSSAuthWebService,
        }
    }
#pragma warning restore 1591
}
