//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.UpdateServices.WebServices.ClientAuthentication
{
#pragma warning disable 1591
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationCookie", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService")]
    public partial class AuthorizationCookie : object
    {
        
        private string PlugInIdField;
        
        private byte[] CookieDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PlugInId
        {
            get
            {
                return this.PlugInIdField;
            }
            set
            {
                this.PlugInIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] CookieData
        {
            get
            {
                return this.CookieDataField;
            }
            set
            {
                this.CookieDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService", ConfigurationName="Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap")]
    public interface SimpleAuthSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService/GetAuth" +
            "orizationCookie", ReplyAction="*")]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieResponse> GetAuthorizationCookieAsync(Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationCookieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationCookie", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService", Order=0)]
        public Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequestBody Body;
        
        public GetAuthorizationCookieRequest()
        {
        }
        
        public GetAuthorizationCookieRequest(Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService")]
    public partial class GetAuthorizationCookieRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string targetGroupName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dnsName;
        
        public GetAuthorizationCookieRequestBody()
        {
        }
        
        public GetAuthorizationCookieRequestBody(string clientId, string targetGroupName, string dnsName)
        {
            this.clientId = clientId;
            this.targetGroupName = targetGroupName;
            this.dnsName = dnsName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationCookieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationCookieResponse", Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService", Order=0)]
        public Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieResponseBody Body;
        
        public GetAuthorizationCookieResponse()
        {
        }
        
        public GetAuthorizationCookieResponse(Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService")]
    public partial class GetAuthorizationCookieResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Microsoft.UpdateServices.WebServices.ClientAuthentication.AuthorizationCookie GetAuthorizationCookieResult;
        
        public GetAuthorizationCookieResponseBody()
        {
        }
        
        public GetAuthorizationCookieResponseBody(Microsoft.UpdateServices.WebServices.ClientAuthentication.AuthorizationCookie GetAuthorizationCookieResult)
        {
            this.GetAuthorizationCookieResult = GetAuthorizationCookieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface SimpleAuthSoapChannel : Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class SimpleAuthSoapClient : System.ServiceModel.ClientBase<Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap>, Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SimpleAuthSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SimpleAuthSoapClient.GetBindingForEndpoint(endpointConfiguration), SimpleAuthSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SimpleAuthSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SimpleAuthSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SimpleAuthSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SimpleAuthSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SimpleAuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieResponse> Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap.GetAuthorizationCookieAsync(Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequest request)
        {
            return base.Channel.GetAuthorizationCookieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieResponse> GetAuthorizationCookieAsync(string clientId, string targetGroupName, string dnsName)
        {
            Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequest inValue = new Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequest();
            inValue.Body = new Microsoft.UpdateServices.WebServices.ClientAuthentication.GetAuthorizationCookieRequestBody();
            inValue.Body.clientId = clientId;
            inValue.Body.targetGroupName = targetGroupName;
            inValue.Body.dnsName = dnsName;
            return ((Microsoft.UpdateServices.WebServices.ClientAuthentication.SimpleAuthSoap)(this)).GetAuthorizationCookieAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SimpleAuthSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SimpleAuthSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SimpleAuthSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SimpleAuthWebService/SimpleAuth.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SimpleAuthSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SimpleAuthWebService/SimpleAuth.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SimpleAuthSoap,
            
            SimpleAuthSoap12,
        }
    }
#pragma warning restore 1591
}
